# Generated by Django 5.2.4 on 2025-08-02 14:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugcrequest',
            name='video_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Типы видео, которые блогер планирует создать', size=None),
        ),
    ]
