# Generated by Django 5.2.4 on 2025-08-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='brands.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BloggerRequest',
        ),
    ]
