# Generated by Django 5.2.4 on 2025-08-02 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_invitation_product_delete_bloggerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
