# Generated by Django 5.2.4 on 2025-08-02 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_product_video_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='video_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Список типов видео, которые запрашивает бренд', size=None),
        ),
    ]
