# Generated by Django 5.2.4 on 2025-08-02 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_invitation_product_delete_bloggerrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('shipping_days', models.IntegerField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('address_provided', 'Адрес введён'), ('shipped', 'Отправлено брендом'), ('received', 'Получено блогером'), ('video_uploaded', 'Видео загружено'), ('verified', 'Видео подтверждено'), ('completed', 'Завершено')], default='address_provided', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_collaborations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.product')),
            ],
        ),
    ]
