# Generated by Django 5.2.4 on 2025-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_bloggerprofile_id_remove_brandprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
