# Generated by Django 5.2.4 on 2025-08-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bloggerprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='blogger_avatar/'),
        ),
    ]
