# Generated by Django 5.2.4 on 2025-09-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bloggerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
